version: 2

models:
  - name: stg_tpch_orders
    columns:
      - name: order_id
        tests: [not_null, unique]

      - name: customer_id
        tests: [not_null]

  - name: stg_tpch_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

      - name: nation_id
        tests: [not_null]
