version: 2

models:
  - name: fct_orders
    description: Final fact table

    columns:
      - name: order_id
        tests:
          - not_null

      - name: total_revenue
        tests:
          - not_null

      - name: customer_id
        tests:
          - not_null